### ISSUE TITLE
How to flash guide

### ISSUE THREAD

**Issue by comigor** [motoxplay/stock#1]
Maybe it would be nice to have a guide/link to a guide of how to flash the `.xml.zip` files. As in [this](http://forum.xda-developers.com/2015-moto-g/general/guide-fastboot-flashing-factory-t3187750) xda thread.

**Comment by mfonville** [comment]
Would indeed be a good idea, but I unfortunately lack the time. If you'd like, you could write something in the README.md with the instructions and give a Pull Request :)

**Comment by SpEcHiDe** [comment]
maybe this could help: https://forum.xda-developers.com/2015-moto-g/general/guide-fastboot-flashing-factory-t3187750
