### ISSUE TITLE
Android Nougat

### ISSUE THREAD

**Issue by SantiiFP2** [motoxplay/stock#15]
I want to know if they are going to upload the Rom of Android 7.0 Nougat for Moto X Play

**Comment by lxwbr** [comment]
[Nougat 7.1 update is rolling out](https://motorola-mobility-en-in.custhelp.com/app/answers/detail/a_id/118842) since 2 days per OTA. Is there any chance of getting an image of it here?

**Comment by brneor** [comment]
At this time I only have the knowledge of an Asian rom. Not sure if the OTA is really rolling out for all users right now.

**Comment by mfonville** [comment]
I found the [soaktest image](https://mega.nz/#!mhBnBARB!CwslFBbhU0bCPFm0G-gWtTkJ74CuUDSH7P7dC_EX-EA) (it was posted on XDA forums)

but this is really a pre-release of very mediocre quality, and for users it is impossible to give any bugreport if not enrolled in the soaktest. So I'd not recommend anyone to flash it at all at this stage (unless the user themselves is part of the soaktest).

**Comment by lucaskoliveira** [comment]
Here in Brazil we're still using version 6.0.1

**Comment by brneor** [comment]
Confirmed that was a soak test pre-release [here](https://forum.xda-developers.com/showpost.php?p=72554507&postcount=549)

**Comment by lxwbr** [comment]
Looks like it's finally out: [droidviews](http://www.droidviews.com/update-moto-x-play-android-7-1-1-nougat/)

EDIT: nvm. seems to be the SOAK version

**Comment by ssparikshya** [comment]
The users are getting updated to 7.1.1 via OTA in India 

By any chance we can have full firmware released here

**Comment by mfonville** [comment]
I have added full firmwares: https://github.com/motoxplay/stock/releases/tag/v7.1.1
