### ISSUE TITLE
6.0.1 images

### ISSUE THREAD

**Issue by piratenpanda** [motoxplay/stock#5]
Hi there, there are 6.0.1 images floating around. Would be nice to have them here too:

http://forum.xda-developers.com/moto-x-play/general/download-moto-x-play-android-6-0-1-t3329332

**Comment by octav-s** [comment]
will add it later today. Thx

**Comment by mfonville** [comment]
We will need to create a new git tag & github release for the 6.0.1 entries

**Comment by mfonville** [comment]
I did put the tag in place: https://github.com/motoxplay/stock/releases/tag/v6.0.1

**Comment by mfonville** [comment]
Added: https://github.com/motoxplay/stock/commit/b04f688182e5dbf1bcc2e9aea8e17cfa3a77ce26

**Comment by mfonville** [comment]
RETLA MPD24.107-52 should also be around, but I was not able to find a "trusted" source for that one yet.

**Comment by mfonville** [comment]
I am now downloading XT1563 RETLA from FileFactory.
If someone else could get: XT1563_LUX_RETAIL_DS_6.0.1_MPD24.107-52_cid12_subsidy-DEFAULT_CFC.xml.zip

**Comment by mfonville** [comment]
I also was able to upload XT1563_LUX_RETAIL
