### ISSUE TITLE
6.0.1 retca available

### ISSUE THREAD

**Issue by piratenpanda** [motoxplay/stock#8]
Either http://www.filefactory.com/file/hf25bkuqpzp/XT1563_LUX_RETCA-BELL_6.0.1_MPD24.107-52_cid14_subsidy-BELLCA_CFC.xml.zip or here https://mega.nz/#!RxlhGZiA!SVmYhuRyUcD0BWZ-VJ2BWL0057iZZuUI9qiIxf3p1uQ

**Comment by mfonville** [comment]
How are these different from the RETCA-Bell that is already offered?
( https://github.com/motoxplay/stock/releases/download/v6.0.1/XT1563_LUX_RETCA-BELL_6.0.1_MPD24.107-52.xml.zip  )

**Comment by piratenpanda** [comment]
Ah sry missed those

**Comment by mfonville** [comment]
@piratenpanda we do need some of the other variants though.
I am currently downloading XT1563_LUX_RETAR-MSTAR from filefactory.
could you maybe download others to collect? http://www.filefactory.com/folder/dd05c058d3ff8dbe/?sort=created&order=DESC&show=100&page=1

**Comment by piratenpanda** [comment]
Am trying to download XT1563_LUX_RETAR_6.0.1_MPD24.107-52_cid12_subsidy-DEFAULT_CFC.xml.zip

**Comment by mfonville** [comment]
@piratenpanda great! :-D

**Comment by piratenpanda** [comment]
I downloaded 7h now, it finished and now the file disappeared. Great...
